### ISSUE TITLE
make temporal.io production ready

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#444]
- production dynamicconfig + remove startup shell script
- fix access to web ui in docker via traefik

**Comment by nics** [comment]
install steps without auto config:

docker-compose up -d

base db setup command: docker exec temporal-admin-tools temporal-sql-tool setup --pl postgres -p 5432 -db temporal_dev —pl postgres -pw W9RhNCDpz2ZkqDNuRbxx9Q7B —ep [mommsen0.ugent.be](http://mommsen0.ugent.be/)

commands: https://github.com/temporalio/temporal/blob/v1.4.1/Makefile#L367-L383

docker exec temporal-admin-tools tctl --ns default namespace register

**Comment by nics** [comment]
example docker compose:

```
docker-compose:

  temporal:
    container_name: temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - DBNAME=temporal_dev
      - VISIBILITY_DBNAME=temporal_visibility_dev
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=xxx
      - POSTGRES_SEEDS=xxx.ugent.be
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yml
    image: temporalio/auto-setup:1.14.0
    ports:
      - 7233
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - my_proxy_network

```
